
name: mern-backend
namespace: mern-ns
replicas: 1
podLabels:
  name: mern-app
  component:  backend-api
container: 
  image: haroonahmed130/k8s-backend
  port: 5000
  # MONGOURI: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-headless:27017/haroondb?authSource=admin
  MONGOURI: mongodb+srv://haroon51166:3vTLrM0s9utvBsp3@cluster0.qrd9uwl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
secret:
  name: mongodb-cred
